version: "3.9"

services:

  conductor-service:
    build: ./conductor-service
    container_name: conductor-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: postgres
      DB_PASSWORD: 324632
      DB_NAME: pwa
      DB_PORT: 5432
    ports:
      - "3000:3000"

  servicio-service:
    build: ./servicio-service
    container_name: servicio-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: postgres
      DB_PASSWORD: 324632
      DB_NAME: pwa
      DB_PORT: 5432
    ports:
      - "3001:3001"

  accion-service:
    build: ./accion-service
    container_name: accion-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: postgres
      DB_PASSWORD: 324632
      DB_NAME: pwa
      DB_PORT: 5432
    ports:
      - "3002:3002"

  evento-service:
    build: ./evento-service
    container_name: evento-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: postgres
      DB_PASSWORD: 324632
      DB_NAME: pwa
      DB_PORT: 5432
    ports:
      - "3003:3003"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8081:8081"
  