version: "3.9"

services:
  conductor-service:
    build: ./conductor-service
    container_name: conductor-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3000:3000"
    networks:
      - p8_network

  servicio-service:
    build: ./servicio-service
    container_name: servicio-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3001:3001"
    networks:
      - p8_network

  accion-service:
    build: ./accion-service
    container_name: accion-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3002:3002"
    networks:
      - p8_network

  evento-service:
    build: ./evento-service
    container_name: evento-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3003:3003"
    networks:
      - p8_network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    networks:
      - p8_network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8081:8081"
    networks:
      - p8_network

networks:
  p8_network:
    driver: bridge
